### ISSUE TITLE
PermissionError [Errno 13]

### ISSUE THREAD

**Issue by lasers** [simonsolnes/ls-acid#2]
`main.py` will trip this error when going through files without permission. I ran into this in `/tmp`.

```
systemd-private-example_dir/Traceback (most recent call last):                                                                                                                                     
  File "/home/chris/src/ls-replacement/main.py", line 369, in <module>
    Files('.').print_files()
  File "/home/chris/src/ls-replacement/main.py", line 366, in print_files
    filename.print_postfix(spaceleft)
  File "/home/chris/src/ls-replacement/main.py", line 189, in print_postfix
    contents = [str(filename) for filename in os.listdir(self.name)]
PermissionError: [Errno 13] Permission denied: 'systemd-private-example_dir'
```

**Comment by simonsolnes** [comment]
Hm thats not good. Do can you run it in sudo maybe?

**Comment by lasers** [comment]
People could do that, I think that would not be a good idea. The script should have something to deal with that... To skip unreadable files/directories along with magenta `(unreadable)` prefix for them.

**Comment by simonsolnes** [comment]
How do you get the issue? My program tries to open a `chmod 000 file`, but nothing happens. No error is thrown.

**Comment by lasers** [comment]
I got this issue by testing `lsa /tmp`. It trips on all three `systemd-private-xxxxx` dirs.

**Comment by simonsolnes** [comment]
I think i fixed it: https://github.com/simonsolnes/ls-acid/commit/cfa51a4e864dde228c4a4267ceeb5e257a9bcb65 Can you please check if it works now?

**Comment by lasers** [comment]
I think it's working okay now. Doesn't trip on `systemd-private-xxxxx` anymore and I still get `print_filecontents` inside `/tmp`. 👍
